### ISSUE TITLE
ImportBlocks plugin for neo 2.9.3 fails

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-plugins#35]
I just installed a fresh copy of neo-cli 2.9.3 and downloaded the latest release of the `ImportBlocks`plugin. Upon starting `neo-cli` I get the follow error:

```
PS D:\neo-cli2.9.3> .\neo-cli.exe
NEO-CLI Version: 2.9.3.0

neo> [ERROR][2018-12-14 11:33:18][Thread 0006][akka://NeoSystem/user/$a] not found
Cause: Neo.IO.Data.LevelDB.LevelDBException (0x80004005): not found
   at Neo.IO.Data.LevelDB.DB.Get(ReadOptions options, Slice key)
   at Neo.IO.Data.LevelDB.Helper.Get[T](DB db, ReadOptions options, Byte prefix, ISerializable key)
   at Neo.Persistence.LevelDB.DbCache`2.GetInternal(TKey key)
   at Neo.IO.Caching.DataCache`2.get_Item(TKey key)
   at Neo.Ledger.Blockchain.Persist(Block block)
   at Neo.Ledger.Blockchain.OnImport(IEnumerable`1 blocks)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[ERROR][2018-12-14 11:33:18][Thread 0006][akka://NeoSystem/user/$a] Error while creating actor instance of type Neo.Ledger.Blockchain with 2 args: (Neo.NeoSystem,Neo.Persistence.LevelDB.LevelDBStore)
Cause: [akka://NeoSystem/user/$a#953832355]: Akka.Actor.PostRestartException: Exception post restart (Neo.IO.Data.LevelDB.LevelDBException) ---> System.TypeLoadException: Error while creating actor instance of type Neo.Ledger.Blockchain with 2 args: (Neo.NeoSystem,Neo.Persistence.LevelDB.LevelDBStore) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.Ledger.Blockchain..ctor(NeoSystem system, Store store)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
PS D:\neo-cli2.9.3>
```

If I remove the `ImportBlocks` plugin, then `neo-cli` works fine.

**Comment by ixje** [comment]
Other observations. When I remove `chain.acc.zip`, then no errors are thrown and also the `plugins` command works. So either way the plugin could be more friendly in handling failures.

**Comment by vncoelho** [comment]
Hi #ixje,

If you want to generate a release with all plugins you can try with this file here: https://github.com/NeoResearch/neo-tests/blob/master/docker-build-neo-cli/env-repositories.sh
You can set to the last commit of the master of all projects.

Maybe something is wrong with the combination of packages.

**Comment by ixje** [comment]
So the latest MainNet offline package from http://sync.ngd.network/ works, while the TestNet offline package does not and throws the errors.

I can extract the TestNet `chain.acc.zip` fine so it is not corrupt.  I compared the md5sum of my download with the sum on the NGD site and they are equal.

**Comment by vncoelho** [comment]
Hi, Ixje, I will close this issue because I think that the problem was related to a problem in the Chain.acc.zip. In addition, some recent changes were made for avoiding errors when plugins are not loaded properly.
Fell free to reopen it if there is any other related issue.
